#!/bin/sh

uci -q set system.@system[0].hostname='ImmortalWrt'
uci -q commit system

for service in tasks quickstart istore; do
	[ -x "/etc/init.d/${service}" ] || continue
	"/etc/init.d/${service}" enable >/dev/null 2>&1
done

rm -rf /tmp/luci-indexcache /tmp/luci-indexcache.* /tmp/luci-modulecache

exit 0
