## This file contains files and directories that should
## be preserved during an upgrade.

/etc/config/homepage_api
/usr/share/rpcd/acl.d/homepage.json
/etc/config/rpcd
/etc/config/openclash
/etc/openclash/
/etc/config/passwall
/etc/config/passwall2
/etc/config/passwall_server
/usr/share/passwall/rules/
/root/cf_optimize/
/opt/open-box/data/
/etc/init.d/openbox
/etc/init.d/openbox-panel
/usr/share/luci/menu.d/luci-app-openbox.json
/usr/share/rpcd/acl.d/luci-app-openbox.json
/www/luci-static/resources/view/openbox/
